# Service definitions for Flashforge Adventurer 5M PRO integration

pause_print:
  name: Pause Print
  description: >-
    Pause the current print job. This will halt the printing process while 
    maintaining temperatures and printer state. The print can be resumed later.
  fields: {}

start_print:
  name: Start Print
  description: >-
    Start a new print job using the specified G-code file. Ensure the file path
    is accessible to the printer and the printer is in a ready state.
  fields:
    file_path:
      name: File Path
      description: >-
        Path to the G-code file on the printer's storage. Must be a valid path
        that the printer can access.
      required: true
      example: "/PrintFiles/model.gcode"
      selector:
        text:

cancel_print:
  name: Cancel Print
  description: >-
    Cancel the current print job. This will stop the print entirely and return
    the printer to an idle state. This action cannot be undone.
  fields: {}

toggle_light:
  name: Toggle Light
  description: >-
    Toggle the printer''s built-in LED light on or off.
  fields:
    state:
      name: State
      description: >-
        The desired state of the light. Set to true to turn the light on,
        false to turn it off.
      required: true
      example: true
      selector:
        boolean:

resume_print:
  name: Resume Print
  description: >-
    Resumes a previously paused print job on the Flashforge printer.
  fields: {} # No fields are needed as it takes no arguments

set_extruder_temperature:
  name: Set Extruder Temperature
  description: >-
    Sets the target temperature for the printer's extruder.
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius.
      required: true
      example: 210
      selector:
        number:
          min: 0
          max: 300 # Adjust max based on printer capability if known, else a safe upper limit
          mode: box # Or slider
          unit_of_measurement: "°C"

set_bed_temperature:
  name: Set Bed Temperature
  description: >-
    Sets the target temperature for the printer's heated bed.
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius.
      required: true
      example: 60
      selector:
        number:
          min: 0
          max: 120 # Adjust max based on printer capability if known, else a safe upper limit
          mode: box # Or slider
          unit_of_measurement: "°C"

set_fan_speed:
  name: Set Fan Speed
  description: >-
    Sets the printer's cooling fan speed. Typically the part cooling fan.
  fields:
    speed:
      name: Speed
      description: Fan speed (0-255). 0 is off, 255 is full speed.
      required: true
      example: 128
      selector:
        number:
          min: 0
          max: 255
          mode: slider # Slider is good for 0-255 range

turn_fan_off:
  name: Turn Fan Off
  description: >-
    Turns the printer's cooling fan off (equivalent to setting speed to 0 with M107).
  fields: {} # No fields needed

move_axis:
  name: Move Axis
  description: >-
    Moves one or more printer axes to the specified coordinates at an optional feedrate.
    Specify at least one axis (x, y, or z). All coordinates are absolute.
  fields:
    x:
      name: X Coordinate
      description: Target X-axis coordinate in mm.
      optional: true
      example: 100.0
      selector:
        number:
          mode: box
          step: 0.1 # Allow for fine control
    y:
      name: Y Coordinate
      description: Target Y-axis coordinate in mm.
      optional: true
      example: 100.0
      selector:
        number:
          mode: box
          step: 0.1
    z:
      name: Z Coordinate
      description: Target Z-axis coordinate in mm.
      optional: true
      example: 50.0
      selector:
        number:
          mode: box
          step: 0.1
    feedrate:
      name: Feedrate
      description: Speed of movement in mm/minute. Printer's default if not specified.
      optional: true
      example: 3000
      selector:
        number:
          min: 0 # Feedrate usually must be positive, coordinator may enforce
          mode: box
          unit_of_measurement: "mm/min"

delete_file:
  name: Delete File
  description: Deletes a specified file from the printer's storage. The file path should be relative to the user directory (e.g., 'my_model.gcode') or an absolute path from the printer's data root if known (e.g., '/data/user/my_model.gcode').
  fields:
    file_path:
      name: File Path
      description: "The path of the file to delete. Examples: 'test.gcode', '/data/user/test.gcode'."
      required: true
      selector:
        text:

disable_steppers:
  name: Disable Stepper Motors
  description: Disables all stepper motors on the printer (M18). This allows manual movement of axes but they will re-engage on the next motion command.
  fields: {} # No fields needed

enable_steppers:
  name: Enable Stepper Motors
  description: Enables all stepper motors on the printer (M17). Stepper motors are typically enabled automatically when a motion command is sent.
  fields: {} # No fields needed

set_speed_percentage:
  name: Set Speed Percentage
  description: Sets the printer's speed factor override (feedrate percentage via M220). Example: S100 is normal speed, S150 is 150%.
  fields:
    percentage:
      name: Percentage
      description: "Speed percentage (e.g., 100 for normal, 150 for 150%). Valid range typically 10-500, but consult printer docs."
      required: true
      selector:
        number:
          min: 10  # Example practical minimum
          max: 500 # Example practical maximum
          mode: slider
          unit_of_measurement: "%"
