# Service definitions for Flashforge Adventurer 5M PRO integration

pause_print:
  name: Pause Print
  description: >-
    Pause the current print job. This will halt the printing process while 
    maintaining temperatures and printer state. The print can be resumed later.
  fields: {}

start_print:
  name: Start Print
  description: >-
    Start a new print job using the specified G-code file. Ensure the file path
    is accessible to the printer and the printer is in a ready state.
  fields:
    file_path:
      name: File Path
      description: >-
        Path to the G-code file on the printer's storage. Must be a valid path
        that the printer can access.
      required: true
      example: "/PrintFiles/model.gcode"
      selector:
        text: {}

cancel_print:
  name: Cancel Print
  description: >-
    Cancel the current print job. This will stop the print entirely and return
    the printer to an idle state. This action cannot be undone.
  fields: {}

toggle_light:
  name: Toggle Light
  description: >-
    Toggle the printer''s built-in LED light on or off.
  fields:
    state: # Note: Changed to 'on' in translations to match boolean typical usage
      name: State
      description: >-
        The desired state of the light. Set to true to turn the light on,
        false to turn it off.
      required: true
      example: true
      selector:
        boolean: {}

resume_print:
  name: Resume Print
  description: >-
    Resumes a previously paused print job on the Flashforge printer.
  fields: {}

set_extruder_temperature:
  name: Set Extruder Temperature
  description: >-
    Sets the target temperature for the printer's extruder.
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius.
      required: true
      example: 210
      selector:
        number:
          min: 0
          max: 300
          mode: box
          unit_of_measurement: "°C"

set_bed_temperature:
  name: Set Bed Temperature
  description: >-
    Sets the target temperature for the printer's heated bed.
  fields:
    temperature:
      name: Temperature
      description: Target temperature in Celsius.
      required: true
      example: 60
      selector:
        number:
          min: 0
          max: 120
          mode: box
          unit_of_measurement: "°C"

set_fan_speed:
  name: Set Fan Speed
  description: >-
    Sets the printer's cooling fan speed. Typically the part cooling fan.
  fields:
    speed:
      name: Speed
      description: Fan speed (0-255). 0 is off, 255 is full speed.
      required: true
      example: 128
      selector:
        number:
          min: 0
          max: 255
          mode: slider

turn_fan_off:
  name: Turn Fan Off
  description: >-
    Turns the printer's cooling fan off (equivalent to setting speed to 0 with M107).
  fields: {}

move_axis:
  name: Move Axis
  description: >-
    Moves one or more printer axes to the specified coordinates at an optional feedrate.
    Specify at least one axis (x, y, or z). All coordinates are absolute.
  fields:
    x:
      name: X Coordinate
      description: Target X-axis coordinate in mm.
      optional: true # Changed from 'required: false' for consistency if that was intended
      selector:
        number: {mode: box, min: 0, max: 220, unit_of_measurement: "mm"} # mode box is often better for direct input
    y:
      name: Y Coordinate
      description: Target Y-axis coordinate in mm.
      optional: true
      selector:
        number: {mode: box, min: 0, max: 220, unit_of_measurement: "mm"}
    z:
      name: Z Coordinate
      description: Target Z-axis coordinate in mm.
      optional: true
      selector:
        number: {mode: box, min: 0, max: 250, unit_of_measurement: "mm"} # Max Z might be different
    feedrate:
      name: Feedrate
      description: Speed of movement in mm/minute. Printer's default if not specified.
      optional: true
      selector:
        number: {mode: box, min: 100, max: 6000, unit_of_measurement: "mm/min"}

delete_file:
  name: Delete File
  description: Deletes a specified file from the printer's storage. The file path should be relative to the user directory (e.g., 'my_model.gcode') or an absolute path like '/data/user/my_model.gcode'.
  fields:
    file_path:
      name: File Path
      description: "The path of the file to delete. Examples: 'test.gcode', '/data/user/test.gcode'."
      required: true
      selector:
        text: {}

disable_steppers:
  name: Disable Stepper Motors
  description: Disables all stepper motors on the printer (M18). This allows manual movement of axes but they will re-engage on the next motion command.
  fields: {}

enable_steppers:
  name: Enable Stepper Motors
  description: Enables all stepper motors on the printer (M17). Stepper motors are typically enabled automatically when a motion command is sent.
  fields: {}

set_speed_percentage:
  name: Set Speed Percentage
  description: Sets the printer's speed factor override (feedrate percentage via M220).
  fields:
    percentage:
      name: Percentage
      description: "Speed percentage (e.g., 100 for normal, 150 for 150%). Valid range typically 10-500, but consult printer docs."
      required: true
      selector:
        number:
          min: 10
          max: 500
          mode: slider
          unit_of_measurement: "%"

set_flow_percentage:
  name: Set Flow Percentage
  description: Sets the printer's extrusion flow rate percentage (M221 S<percentage>).
  fields:
    percentage:
      name: Percentage
      description: "Flow percentage (e.g., 100 for normal). Typical range 50-200."
      required: true
      selector:
        number:
          min: 50
          max: 200
          mode: slider
          unit_of_measurement: "%"

home_axes:
  name: Home Axes
  description: Homes one or more axes (G28). If no axes are specified, all axes are homed.
  fields:
    axes: # Changed from individual x,y,z booleans to a list of strings for flexibility
      name: Axes
      description: "Optional list of axes to home (e.g., ['X', 'Y']). If omitted or empty, all axes are homed."
      required: false # Making it not required means all axes if omitted
      example: ["X", "Y"]
      selector:
        object: {} # Represents a list; specific selector for list of strings might need custom handling or rely on text input of comma-separated values if UI supports. For services.yaml, 'object' is generic.

filament_change:
  name: Filament Change
  description: Initiates the filament change procedure (M600). Behavior depends on printer firmware.
  fields: {}

emergency_stop:
  name: Emergency Stop
  description: Immediately halts all printer operations (M112). Use with extreme caution.
  fields: {}

save_settings_to_eeprom:
  name: Save Settings to EEPROM
  description: Saves current settings to printer's EEPROM (via M500).
  fields: {}

restore_factory_settings:
  name: Restore Factory Settings
  description: Restores printer to factory default settings (M502). Use with extreme caution; this may erase calibration.
  fields: {}

list_files:
  name: List Files
  description: "Lists files on the printer's storage (via M20). The full list is logged at DEBUG level by the integration, a summary may be logged at INFO level."
  fields: {}

report_firmware_capabilities:
  name: Report Firmware Capabilities
  description: "Requests and logs the printer's firmware version and capabilities (via M115). The full report is logged at DEBUG level, a summary may be logged at INFO level."
  fields: {}

play_beep:
  name: Play Beep
  description: "Plays a beep sound on the printer (via M300)."
  fields:
    pitch:
      name: "Pitch"
      description: "Frequency of the beep in Hz."
      required: true
      example: 1000
      selector:
        number:
          min: 0
          max: 10000
          mode: box
          unit_of_measurement: "Hz"
    duration:
      name: "Duration"
      description: "Duration of the beep in milliseconds."
      required: true
      example: 500
      selector:
        number:
          min: 0
          max: 10000
          mode: box
          unit_of_measurement: "ms"

start_bed_leveling:
  name: Start Bed Leveling
  description: "Initiates the automatic bed leveling procedure (via G29). Behavior can vary based on printer firmware."
  fields: {}

read_settings_from_eeprom:
  name: Read Settings from EEPROM
  description: "Reads current settings from EEPROM (via M501) and logs them. The full output is logged at DEBUG level, a summary may be logged at INFO level."
  fields: {}

move_relative:
  name: Move Relative
  description: "Moves printer axes by a relative amount. Specify at least one axis. Printer returns to absolute G-code mode afterwards."
  fields:
    x:
      name: X Offset
      description: "Relative move for X-axis (mm). Positive or negative."
      optional: true
      example: 10.0
      selector:
        number:
          mode: box
          step: 0.1
    y:
      name: Y Offset
      description: "Relative move for Y-axis (mm). Positive or negative."
      optional: true
      example: -5.5
      selector:
        number:
          mode: box
          step: 0.1
    z:
      name: Z Offset
      description: "Relative move for Z-axis (mm). Positive or negative."
      optional: true
      example: 1.0
      selector:
        number:
          mode: box
          step: 0.1
    feedrate:
      name: Feedrate
      description: "Speed for this relative move (mm/min). Optional. Uses printer default if not set."
      optional: true
      example: 1500
      selector:
        number:
          mode: box
          min: 100
          max: 6000
          unit_of_measurement: "mm/min"

send_gcode:
  name: Send G-code Command
  description: >-
    Sends a raw G-code command directly to the printer.
    Use with caution, as improper commands can cause issues.
    Commands should typically be prefixed with '~' if required by the printer for M-codes/G-codes via TCP.
  fields:
    gcode_command:
      name: G-code Command
      description: "The raw G-code string to send to the printer (e.g., '~M105' or 'G28 X Y')."
      required: true
      example: "~M117 Hello World"
      selector:
        text: {}
